### ISSUE TITLE
Fontsize

### ISSUE THREAD

**Issue by CyclingJack** [pgdurand/jGAF#8]
Hello,
I am programming a billing programme for my IT project and I am using jGAF. 
I have developed an application interface that loads the appropriate JPanel via the respective menu selection. 
After viewing the application on another computer, I noticed that the font of the menus and the dialogues is very small. 
Is there a way to directly influence and adjust the font size in the menus, the dialogue boxes and the headline of the window?

**Comment by CyclingJack** [comment]
![image](https://user-images.githubusercontent.com/27978484/191074431-5b753a93-654f-472b-b22e-9665885a1df0.png)

**Comment by pgdurand** [comment]
Hi,

actually, a default main font is defined using SanSerif, plain, 12 point size (see MAINFONT constant in class EZEnvironmentImplem in package com.plealog.genericapp.ui.starter). 

The way to override that default font is to use a RessourceBundle file, actually the one you use to setup your menu definition. There, you can define "app.font.name" and "app.font.size" keys to setup font name and size, respectively. 

Patrick

**Comment by CyclingJack** [comment]
Hello,
thank you very much for the quick answer. 
I tried that, but it doesn't work.
I have looked in the class EZActionManager. There, in line 424, the font and size of the menu is set with menu.setFont(EZEnvironmentImplem.getMainFont(null).
In the class EZEnvironmentImplem, however, a ResourceBundle rb is expected as a transfer parameter in the method. 
In the method, line 314 is explicitly checked again for null, which leads to the variable fnt not being changed.
The standard font defined in the class EZEnvironmentImplem in the variable MAINFONT is passed and used here.
If I call the method EZEnvironmentImplem.getMainFont() with null for a test, the standard font SansSerif 12 Planin is returned.
If I call the method with the previously created ResoruceBundle, in this case the properties file in which the menu items are also located, the font correctly named in it is returned.

**Comment by pgdurand** [comment]
Hi,

I'm quite in trouble modifying that: I work on macOS and jGAF uses native Desktop integration... so menu size is set by macOS, not Java. I've tried several examples, and menu size can only be programmatically changed by Java code if menu is added to main JFrame ; i.e. menu is part of the main frame, not integrated in standard macOS Desktop menu. 

Patrick

**Comment by pgdurand** [comment]
Fix in latest 2.4.2 release ; code added to handle font changes using standard Swing UIManger stuffs.
