### ISSUE TITLE
EZEnvironment Class

### ISSUE THREAD

**Issue by CyclingJack** [pgdurand/jGAF#9]
Hello Patrick,
It's me again, I hope you're not annoyed :-)
I don't know if you are still interested in further development or bug fixing.
I think jGAF is a good and very lean approach for a Swing application framework. 

I use it with Netbeans, which requires a bit of manual work at one point or another.

I discovered another typo. 
In the Environment class there is the method removeResourceLocatro and you surely meant removeResourceLocator.

Best regards
Andreas

**Comment by pgdurand** [comment]
fixed... will be available in a future relase.

(no, you're not annoying me... in turn, I should apologize for the delay of my answer! ;-) )

**Comment by pgdurand** [comment]
Fix in latest 2.4.2 release
